export const units = [
    { value: "envelope", labelEn: "Envelope", labelAr: "ظرف" },
    { value: "bag", labelEn: "Bag", labelAr: "كيس" },
    { value: "can", labelEn: "Can", labelAr: "علبة" },
    { value: "piece", labelEn: "Piece", labelAr: "قطعة" },
    { value: "unit", labelEn: "Unit", labelAr: "وحدة" },
    { value: "bottle", labelEn: "Bottle", labelAr: "زجاجة" },
    { value: "pack", labelEn: "Pack", labelAr: "عبوة" },
    { value: "gram", labelEn: "Gram", labelAr: "جرام" },
    { value: "kilogram", labelEn: "Kilogram", labelAr: "كيلو جرام" },
    { value: "liter", labelEn: "Liter", labelAr: "لتر" },
    { value: "jerrycan", labelEn: "Jerrycan", labelAr: "جركن" },
    { value: "set", labelEn: "Set", labelAr: "طقم" },
    { value: "dozen", labelEn: "Dozen", labelAr: "دستة" },
    { value: "roll", labelEn: "Roll", labelAr: "لفة" },
    { value: "bundle", labelEn: "Bundle", labelAr: "حزمة" },
    { value: "package", labelEn: "Package", labelAr: "رزمة" },
    { value: "pallet", labelEn: "Pallet", labelAr: "بالتة" },
    { value: "shrink", labelEn: "Shrink", labelAr: "شرنك" },
    { value: "carton", labelEn: "Carton", labelAr: "كرتونة" },
    { value: "box", labelEn: "Box", labelAr: "صندوق" },
    { value: "sack", labelEn: "Sack", labelAr: "شكارة" },
    { value: "ton", labelEn: "Ton", labelAr: "طن" },
    { value: "milliliter", labelEn: "Milliliter", labelAr: "ملليتر" },
    { value: "volt", labelEn: "Volt", labelAr: "فولت" },
    { value: "ampere", labelEn: "Ampere", labelAr: "امبير" },
    { value: "square_meter", labelEn: "Square Meter", labelAr: "متر مربع" },
    { value: "inch", labelEn: "Inch", labelAr: "بوصة" },
    { value: "sheet", labelEn: "Sheet", labelAr: "فرخ" },
    { value: "barrel", labelEn: "Barrel", labelAr: "برميل" },
    { value: "jar", labelEn: "Jar", labelAr: "برطمان" },
];
