export const enLabels = {
    "/dashboard": "Dashboard",
    "/dashboard/divisions/follow-up": "Purchases & Follow-Ups",
    "/dashboard/divisions/follow-up/supplier-joining-requests": "Joining Requests",
    "/dashboard/divisions/follow-up/supplier-order-tracking": "Supplier Order Tracking",
    "/dashboard/divisions/follow-up/purchase": "Purchases",
    "/dashboard/divisions/follow-up/complains": "Complains",
    "/dashboard/divisions/customer-service": "Customer Service",
    "/dashboard/divisions/customer-service/join-requests": "Joining Requests",
    "/dashboard/divisions/customer-service/order-tracking": "Order Tracking",
    "/dashboard/divisions/customer-service/complains": "Complains",
    "/dashboard/divisions/receiving-completion": "Receiving & Completion",
    "/dashboard/divisions/receiving-completion/receive": "Receiving & Inspection",
    "/dashboard/divisions/receiving-completion/returns": "Returns",
    "/dashboard/divisions/receiving-completion/complains": "Complains",
    "/dashboard/divisions/shipping": "Shipping Management",
    "/dashboard/divisions/shipping/order-shipping": "Order Shipping",
    "/dashboard/divisions/shipping/order-pickup": "Order Pickup",
    "/dashboard/divisions/shipping/complains": "Complains",
    "/dashboard/divisions/storage": "Storage Management",
    "/dashboard/divisions/storage/process": "Process",
    "/dashboard/divisions/storage/returns": "Returns",
    "/dashboard/divisions/storage/complains": "Complains",
    "/dashboard/divisions/accounting": "Accounting",
    "/dashboard/divisions/accounting/receipts": "Receipts and Invoices",
    "/dashboard/divisions/accounting/supplier-transactions": "Supplier's Transactions",
    "/dashboard/divisions/accounting/client-transactions": "Client's Transactions",
    "/dashboard/divisions/accounting/complains": "Complains",
    "/dashboard/divisions/marketing": "Marketing",
    "/dashboard/divisions/marketing/general": "General",
    "/dashboard/divisions/complains":" Complains and Suggestions",
    "/dashboard/divisions/complains/general": "General",
    "/dashboard/management": "Management",
    "/dashboard/management/employees": "Employees",
    "/dashboard/management/suppliers": "Suppliers",
    "/dashboard/management/clients": "Clients",
    "/dashboard/management/products": "Products",
    "/dashboard/management/branches": "Branches",
    
    // "/dashboard/products": "Products",
    // "/dashboard/products/[id]": "Product",
}

export const arLabels = {
    "/dashboard": "لوحة التحكم",
    "/dashboard/divisions": "الأقسام",
    "/dashboard/divisions/follow-up": "المشتريات والمتابعة",
    "/dashboard/divisions/follow-up/supplier-joining-requests": "طلبات الإنضمام",
    "/dashboard/divisions/follow-up/supplier-order-tracking": "تتبع طلبات الموردين",
    "/dashboard/divisions/follow-up/purchase": "المشتريات",
    "/dashboard/divisions/follow-up/complains": "الشكاوى",
    "/dashboard/divisions/customer-service": "خدمة العملاء",
    "/dashboard/divisions/customer-service/join-requests": "طلبات الإنضمام",
    "/dashboard/divisions/customer-service/order-tracking": "تتبع طلبات العملاء",
    "/dashboard/divisions/customer-service/complains": "الشكاوى",
    "/dashboard/divisions/receiving-completion": "الفحص و المراجعة",
    "/dashboard/divisions/receiving-completion/receive": "الإستلام والفحص",
    "/dashboard/divisions/receiving-completion/returns": "المرتجعات",
    "/dashboard/divisions/receiving-completion/complains": "الشكاوى",
    "/dashboard/divisions/shipping": "الشحن والتحصيل",
    "/dashboard/divisions/shipping/order-shipping": "شحن الطلبات",
    "/dashboard/divisions/shipping/order-pickup": "استلام الطلبات",
    "/dashboard/divisions/shipping/complains": "الشكاوى",
    "/dashboard/divisions/storage": "المخزن",
    "/dashboard/divisions/storage/process": "المعالجة",
    "/dashboard/divisions/storage/returns": "المرتجعات",
    "/dashboard/divisions/storage/complains": "الشكاوى",
    "/dashboard/divisions/accounting": "الحسابات والمالية",
    "/dashboard/divisions/accounting/receipts": "الإيصالات والفواتير",
    "/dashboard/divisions/accounting/supplier-transactions": "معاملات الموردين",
    "/dashboard/divisions/accounting/client-transactions": "معاملات العملاء",
    "/dashboard/divisions/accounting/complains": "الشكاوى",
    "/dashboard/divisions/marketing": "التسويق",
    "/dashboard/divisions/marketing/general": "عام",
    "/dashboard/divisions/complains":"الشكاوى والمقترحات",
    "/dashboard/divisions/complains/general": "عام",
    "/dashboard/management": "الإدارة",
    "/dashboard/management/employees": "الموظفين",
    "/dashboard/management/suppliers": "الموردين",
    "/dashboard/management/clients": "العملاء",
    "/dashboard/management/products": "المنتجات",
    "/dashboard/management/branches": "الفروع",

    // "/dashboard/products": "المنتجات",
    // "/dashboard/products/[id]": "منتج",
}

// export const dynamic = {}
//     if (productId && productName) {
//         dynamic[`/dashboard/products/${productId}`] = productName
//     }
